/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MINIPROYECTO;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author Administrator
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    private FormularioContacto formularioContacto;
    private JPanel panelPrincipal;
   
    public ventanaPrincipal() {
        initComponents();
        formularioContacto = new FormularioContacto();
        panelPrincipal = new JPanel();
        
        panelPrincipal.setLayout(new BorderLayout());
        panelPrincipal.add(panelBuscar, BorderLayout.NORTH);
        panelPrincipal.add(jScrollPane1, BorderLayout.CENTER);

        panelPrincipal.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        setContentPane(panelPrincipal); 
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
        
        //JTable
        //Definir los nombres de las columnas
        String[] columnas = {"Nombre", "Apellido", "Telefono", "Correo", "Direccion", "Estado Civil"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
        jTable1.setModel(modeloTabla);
       
        ImageIcon icono = new ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\lupa.png");
        Image imagen = icono.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        icono = new ImageIcon(imagen);

        botonBuscar.setIcon(icono);
        
        setFocusable(true);              
        requestFocusInWindow();  

        //Agregar KeyListener para jTable1
        jTable1.addKeyListener(new KeyAdapter() { 
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_E) {
                    MenuItemEditarActionPerformed(null);
                }
            }
        });
        

        jTable1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_N) {
                    mostrarFormularioContacto();
                }
            }
        });
        
        jTable1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_D) {
                    MenuItemEliminarActionPerformed(null);
                }
            }
        });
        


        setFocusable(true);
        requestFocusInWindow();
        
        jTable1.setFocusable(true);
        jTable1.requestFocusInWindow();
        
    }

    private void salirPrograma() {
        int respuesta = JOptionPane.showConfirmDialog(
            null,
            "¿Estas seguro de que deseas salir?",
            "Confirmar Salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    public void agregarContacto(String nombre, String apellido, String telefono, String correo, String direccion, String estadoCivil) {
        DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
        modeloTabla.addRow(new Object[] {nombre, apellido, telefono, correo, direccion, estadoCivil});
    }
    
    private void mostrarFormularioContacto() {
        panelPrincipal.removeAll();
        panelPrincipal.add(formularioContacto, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }
    
    
    public void mostrarVentanaPrincipal() {
        panelPrincipal.removeAll(); 
        panelPrincipal.setLayout(new BorderLayout());
        panelPrincipal.add(jScrollPane1, BorderLayout.CENTER); 
        panelPrincipal.add(panelBuscar, BorderLayout.NORTH); 
        panelPrincipal.revalidate(); 
        panelPrincipal.repaint(); 
    }
    
    private void filtrarPorTelefono(String telefono) {
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) jTable1.getModel());
        jTable1.setRowSorter(sorter);

        if(telefono.trim().length() == 0){
            sorter.setRowFilter(null);
        }else{
            sorter.setRowFilter(RowFilter.regexFilter(telefono));
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelBuscar = new java.awt.Panel();
        campoBuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        MenuItemAgregar = new javax.swing.JMenuItem();
        MenuItemEditar = new javax.swing.JMenuItem();
        MenuItemEliminar = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuItemArchivoGuardar = new javax.swing.JMenuItem();
        menuItemArchivoSalir = new javax.swing.JMenuItem();
        MenuItemAcercaDe = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de contactos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        campoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscarActionPerformed(evt);
            }
        });

        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addComponent(campoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu6.setText("Contactos");

        MenuItemAgregar.setText("Agregar");
        MenuItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAgregarActionPerformed(evt);
            }
        });
        jMenu6.add(MenuItemAgregar);

        MenuItemEditar.setText("Editar");
        MenuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditarActionPerformed(evt);
            }
        });
        jMenu6.add(MenuItemEditar);

        MenuItemEliminar.setText("Eliminar");
        MenuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEliminarActionPerformed(evt);
            }
        });
        jMenu6.add(MenuItemEliminar);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Archivo");

        menuItemArchivoGuardar.setText("Guardar");
        menuItemArchivoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemArchivoGuardarActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemArchivoGuardar);

        menuItemArchivoSalir.setText("Salir");
        menuItemArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemArchivoSalirActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemArchivoSalir);

        jMenuBar1.add(jMenu7);

        MenuItemAcercaDe.setText("Ayuda");
        MenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAcercaDeActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Acerca de");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuItemAcercaDe.add(jMenuItem5);

        jMenuBar1.add(MenuItemAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JOptionPane.showMessageDialog(null, 
        "CREADO POR MARIANA ALZATE BARBOSA - CORTE 2 POO", 
        "Acerca de", 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void MenuItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int filaSeleccionada = jTable1.getSelectedRow();
        if(filaSeleccionada != -1){
            int respuesta = JOptionPane.showConfirmDialog(
                    this,
                    "¿Quieres editar este contacto?",
                    "Editar",
                    JOptionPane.YES_NO_OPTION
            );
            if (respuesta == JOptionPane.YES_OPTION) {
                //Obtener los datos de la fila seleccionada
                String nombre = (String) modelo.getValueAt(filaSeleccionada, 0);
                String apellido = (String) modelo.getValueAt(filaSeleccionada, 1);
                String telefono = (String) modelo.getValueAt(filaSeleccionada, 2);
                String correo = (String) modelo.getValueAt(filaSeleccionada, 3);
                String direccion = (String) modelo.getValueAt(filaSeleccionada, 4);
                String estadoCivil = (String) modelo.getValueAt(filaSeleccionada, 5);

                //llenar los campos del formulario
                formularioContacto.getCampo1Nombre().setText(nombre);
                formularioContacto.getCampo2Apellido().setText(apellido);
                formularioContacto.getCampo3Telefono().setText(telefono);
                formularioContacto.getCampo4Correo().setText(correo);
                formularioContacto.getCampo5Direccion().setText(direccion);

                //establecer el estado civil en el formulario con el setter general
                formularioContacto.setEstadoCivil(estadoCivil);

                mostrarFormularioContacto();
                modelo.removeRow(filaSeleccionada);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un contacto para editar.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_MenuItemEditarActionPerformed

    private void MenuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEliminarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel(); //
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            int respuesta = JOptionPane.showConfirmDialog(
                   this,
                   "¿Estas seguro de que deseas eliminar esta fila?",
                   "Confirmacion de eliminacion",
                   JOptionPane.YES_NO_OPTION
            );
            if (respuesta == JOptionPane.YES_OPTION) {
               modelo.removeRow(filaSeleccionada);
               JOptionPane.showMessageDialog(this, "Fila eliminada correctamente.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            }
        }else {
          JOptionPane.showMessageDialog(this, "Por favor selecciona una fila para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_MenuItemEliminarActionPerformed

    private void MenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAcercaDeActionPerformed

    }//GEN-LAST:event_MenuItemAcercaDeActionPerformed

    private void menuItemArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemArchivoSalirActionPerformed
        salirPrograma();
    }//GEN-LAST:event_menuItemArchivoSalirActionPerformed

    private void campoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscarActionPerformed

    }//GEN-LAST:event_campoBuscarActionPerformed

    private void MenuItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAgregarActionPerformed
        mostrarFormularioContacto();
    }//GEN-LAST:event_MenuItemAgregarActionPerformed

    private void menuItemArchivoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemArchivoGuardarActionPerformed
        JOptionPane.showMessageDialog(null, "Se guardo la informacion", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuItemArchivoGuardarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String telefono = campoBuscar.getText();
        filtrarPorTelefono(telefono);
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventanaPrincipal ventana = new ventanaPrincipal(); 
                ventana.setVisible(true);
                ventana.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuItemAcercaDe;
    private javax.swing.JMenuItem MenuItemAgregar;
    private javax.swing.JMenuItem MenuItemEditar;
    private javax.swing.JMenuItem MenuItemEliminar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem menuItemArchivoGuardar;
    private javax.swing.JMenuItem menuItemArchivoSalir;
    private java.awt.Panel panelBuscar;
    // End of variables declaration//GEN-END:variables
}
