/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PUNTO1;

import com.google.gson.Gson;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.Element;
import javax.xml.parsers.DocumentBuilderFactory;

/**
 *
 * @author ItRoy
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }
    
    
    public String[] leerTXT(){
        try{
            File file = new File("D:\\Documents\\NetBeansProjects\\PARCIAL\\personas.txt");
            FileReader leer = new FileReader(file);
            BufferedReader bufferedReader = new BufferedReader(leer);
            String linea;
            linea = bufferedReader.readLine();

            while(linea != null){
                System.out.println(linea);
                
            }
            bufferedReader.close();

        } catch (IOException ex) {
            Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
        }  
        return null;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGuardarTXT = new javax.swing.JButton();
        botonLeerXML = new javax.swing.JButton();
        botonGuardarXML = new javax.swing.JButton();
        botonLeerTXT = new javax.swing.JButton();
        botonGuardarJSON = new javax.swing.JButton();
        botonLeerJSON = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFormulario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonGuardarTXT.setText("GUARDAR TXT");
        botonGuardarTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarTXTMouseClicked(evt);
            }
        });
        botonGuardarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarTXTActionPerformed(evt);
            }
        });

        botonLeerXML.setText("LEER XML");
        botonLeerXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLeerXMLActionPerformed(evt);
            }
        });

        botonGuardarXML.setText("GUARDAR XML");
        botonGuardarXML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarXMLMouseClicked(evt);
            }
        });
        botonGuardarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarXMLActionPerformed(evt);
            }
        });

        botonLeerTXT.setText("LEER TXT");
        botonLeerTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLeerTXTMouseClicked(evt);
            }
        });
        botonLeerTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLeerTXTActionPerformed(evt);
            }
        });

        botonGuardarJSON.setText("GUARDAR JSON");
        botonGuardarJSON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarJSONMouseClicked(evt);
            }
        });

        botonLeerJSON.setText("LEER JSON");
        botonLeerJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLeerJSONActionPerformed(evt);
            }
        });

        tablaFormulario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CORREO"
            }
        ));
        jScrollPane1.setViewportView(tablaFormulario);

        jLabel1.setText("NOMBRE: ");

        jLabel2.setText("IDENTIFICACION:");

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("CORREO:");

        jLabel4.setText("BIENVENIDO AL FORMULARIO DE USUARIO!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonGuardarTXT)
                                    .addComponent(botonLeerTXT))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonGuardarXML)
                                    .addComponent(botonLeerXML)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(campoId, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1))
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoNombre)
                                        .addComponent(campoCorreo)))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonGuardarJSON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonLeerJSON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel4)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarTXT)
                    .addComponent(botonGuardarXML)
                    .addComponent(botonGuardarJSON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLeerXML)
                    .addComponent(botonLeerTXT)
                    .addComponent(botonLeerJSON))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarTXTActionPerformed

    private void botonLeerXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLeerXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLeerXMLActionPerformed

    private void botonGuardarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarXMLActionPerformed

    private void botonLeerTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLeerTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLeerTXTActionPerformed

    private void botonLeerJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLeerJSONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLeerJSONActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void botonGuardarTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarTXTMouseClicked
        String id = campoId.getText();
        String nombre = campoNombre.getText();
        String correo = campoCorreo.getText();
        
        try{
            
            File file = new File("personas.txt");
            file.createNewFile();
            FileWriter writer = new FileWriter(file);
            BufferedWriter bufferedWriter = new BufferedWriter(writer);
            bufferedWriter.write(id);
            bufferedWriter.write("\n"+nombre);
            bufferedWriter.write("\n"+correo+"\n");
            bufferedWriter.close();
            
        } catch (IOException ex) {
            Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        campoId.setText("");
        campoNombre.setText("");
        campoCorreo.setText("");
        
    }//GEN-LAST:event_botonGuardarTXTMouseClicked

    private void botonLeerTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLeerTXTMouseClicked
        leerTXT();
    }//GEN-LAST:event_botonLeerTXTMouseClicked

    private void botonGuardarJSONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarJSONMouseClicked
        String id = campoId.getText();
        String nombre = campoNombre.getText();
        String correo = campoCorreo.getText();

        try{
            File file = new File("personas.json");
            file.createNewFile();
            FileWriter writer = new FileWriter(file);
            BufferedWriter bufferedWriter = new BufferedWriter(writer);
            Gson gson = new Gson();
            String identi = gson.toJson(id);
            String name = gson.toJson(nombre);
            String email = gson.toJson(correo);
            bufferedWriter.write(identi);
            bufferedWriter.write(name);
            bufferedWriter.write(email);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_botonGuardarJSONMouseClicked

    private void botonGuardarXMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarXMLMouseClicked
        String id = campoId.getText();
        String nombre = campoNombre.getText();
        String correo = campoCorreo.getText();
        
        try{
            DocumentBuilderFactory factory = new DocumentBuilderFactory();
            BuilderFactory builderFactory = factory;
            Element raiz = new Element();
        }
    }//GEN-LAST:event_botonGuardarXMLMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarJSON;
    private javax.swing.JButton botonGuardarTXT;
    private javax.swing.JButton botonGuardarXML;
    private javax.swing.JButton botonLeerJSON;
    private javax.swing.JButton botonLeerTXT;
    private javax.swing.JButton botonLeerXML;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFormulario;
    // End of variables declaration//GEN-END:variables
}
