/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemploKeyType;

import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Administrator
 */
public class miniCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form miniCalculadora
     */
    public miniCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoResultado = new javax.swing.JTextField();
        botonNumero1 = new javax.swing.JButton();
        campoNumero2 = new javax.swing.JTextField();
        campoNumero1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonResultado = new javax.swing.JButton();
        botonNumero2 = new javax.swing.JButton();
        botonNumero3 = new javax.swing.JButton();
        botonNumero0 = new javax.swing.JButton();
        botonNumero4 = new javax.swing.JButton();
        botonNumero5 = new javax.swing.JButton();
        botonNumero6 = new javax.swing.JButton();
        botonNumero7 = new javax.swing.JButton();
        botonNumero8 = new javax.swing.JButton();
        botonNumero9 = new javax.swing.JButton();
        botonSuma = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        botonMultiplicacion = new javax.swing.JButton();
        botonDivision = new javax.swing.JButton();
        campoSimbolo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        campoResultado.setFocusable(false);
        campoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoResultadoActionPerformed(evt);
            }
        });

        botonNumero1.setText("1");
        botonNumero1.setFocusable(false);
        botonNumero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNumero1MouseClicked(evt);
            }
        });
        botonNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero1ActionPerformed(evt);
            }
        });

        campoNumero2.setFocusable(false);
        campoNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero2ActionPerformed(evt);
            }
        });

        campoNumero1.setFocusable(false);

        jLabel1.setText("MINI CALCULADORA");

        botonResultado.setText("RESULTADO");
        botonResultado.setFocusable(false);
        botonResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonResultadoMouseClicked(evt);
            }
        });
        botonResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResultadoActionPerformed(evt);
            }
        });

        botonNumero2.setText("2");
        botonNumero2.setFocusable(false);
        botonNumero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNumero2MouseClicked(evt);
            }
        });
        botonNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero2ActionPerformed(evt);
            }
        });

        botonNumero3.setText("3");
        botonNumero3.setFocusable(false);
        botonNumero3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNumero3MouseClicked(evt);
            }
        });
        botonNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero3ActionPerformed(evt);
            }
        });

        botonNumero0.setText("0");
        botonNumero0.setFocusable(false);
        botonNumero0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNumero0MouseClicked(evt);
            }
        });
        botonNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero0ActionPerformed(evt);
            }
        });

        botonNumero4.setText("4");
        botonNumero4.setFocusable(false);
        botonNumero4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNumero4MouseClicked(evt);
            }
        });
        botonNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero4ActionPerformed(evt);
            }
        });

        botonNumero5.setText("5");
        botonNumero5.setFocusable(false);
        botonNumero5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNumero5MouseClicked(evt);
            }
        });
        botonNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero5ActionPerformed(evt);
            }
        });

        botonNumero6.setText("6");
        botonNumero6.setFocusable(false);
        botonNumero6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNumero6MouseClicked(evt);
            }
        });
        botonNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero6ActionPerformed(evt);
            }
        });

        botonNumero7.setText("7");
        botonNumero7.setFocusable(false);
        botonNumero7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNumero7MouseClicked(evt);
            }
        });
        botonNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero7ActionPerformed(evt);
            }
        });

        botonNumero8.setText("8");
        botonNumero8.setFocusable(false);
        botonNumero8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNumero8MouseClicked(evt);
            }
        });
        botonNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero8ActionPerformed(evt);
            }
        });

        botonNumero9.setText("9");
        botonNumero9.setFocusable(false);
        botonNumero9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNumero9MouseClicked(evt);
            }
        });
        botonNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumero9ActionPerformed(evt);
            }
        });

        botonSuma.setText("+");
        botonSuma.setFocusable(false);
        botonSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSumaMouseClicked(evt);
            }
        });
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });

        botonResta.setText("-");
        botonResta.setFocusable(false);
        botonResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRestaMouseClicked(evt);
            }
        });
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });

        botonMultiplicacion.setText("*");
        botonMultiplicacion.setFocusable(false);
        botonMultiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMultiplicacionMouseClicked(evt);
            }
        });
        botonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicacionActionPerformed(evt);
            }
        });

        botonDivision.setText("/");
        botonDivision.setFocusable(false);
        botonDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDivisionMouseClicked(evt);
            }
        });
        botonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivisionActionPerformed(evt);
            }
        });

        campoSimbolo.setFocusable(false);
        campoSimbolo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoSimboloMouseClicked(evt);
            }
        });
        campoSimbolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSimboloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonNumero5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(campoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(botonResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(campoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSuma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonResta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMultiplicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDivision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(botonResultado)
                .addGap(18, 18, 18)
                .addComponent(campoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    boolean operacionSeleccionada = false; 
    
    private void botonNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero1ActionPerformed

    private void campoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoResultadoActionPerformed

    private void botonResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonResultadoActionPerformed

    private void campoNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumero2ActionPerformed

    private void botonNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero2ActionPerformed

    private void botonNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero3ActionPerformed

    private void botonNumero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNumero1MouseClicked
        if(!operacionSeleccionada) {
            if (campoNumero1.getText().equals("")){
                campoNumero1.setText("1");
            }
        }else{
            if(campoNumero2.getText().equals("")){
                campoNumero2.setText("1");
            }
        }   
    }//GEN-LAST:event_botonNumero1MouseClicked

    private void botonNumero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNumero2MouseClicked
        if(!operacionSeleccionada) {
            if (campoNumero1.getText().equals("")){
                campoNumero1.setText("2");
            }
        }else{
            if(campoNumero2.getText().equals("")){
                campoNumero2.setText("2");
            }
        }        
    }//GEN-LAST:event_botonNumero2MouseClicked

    private void botonNumero3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNumero3MouseClicked
        if(!operacionSeleccionada) {
            if (campoNumero1.getText().equals("")){
                campoNumero1.setText("3");
            }
        }else{
            if(campoNumero2.getText().equals("")){
                campoNumero2.setText("3");
            }
        }          
    }//GEN-LAST:event_botonNumero3MouseClicked

    private void botonResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonResultadoMouseClicked
        if(!campoNumero1.getText().equals("") && !campoNumero2.getText().equals("")){
            int numero1 = Integer.parseInt(campoNumero1.getText());
            int numero2 = Integer.parseInt(campoNumero2.getText());
            int resultado = 0;

            
            switch(campoSimbolo.getText()){
                case "+":
                    resultado = numero1+numero2;
                    break;
                case "-":
                    resultado = numero1-numero2;
                    break;
                case "*":
                    resultado = numero1*numero2;
                    break;
                case "/":
                    if(numero2 != 0){
                        resultado = numero1/numero2;
                    }else{
                        JOptionPane.showMessageDialog(null, "NO SE PUEDE DIVIDIR ENTRE O", "ERROR", JOptionPane.ERROR_MESSAGE);
                        campoNumero1.setText("");
                        campoSimbolo.setText("");
                        campoNumero2.setText("");
                        campoResultado.setText("");
                        operacionSeleccionada = false;
                        return;
                    }
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "no se pudo realizar la operacion", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return;
            }
            
            campoResultado.setText("Resultado: "+ resultado);
            campoNumero1.setText("");
            campoNumero2.setText("");
            campoSimbolo.setText("");
            operacionSeleccionada = false;
        }
    }//GEN-LAST:event_botonResultadoMouseClicked

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        String numero = String.valueOf(evt.getKeyChar());
        if(numero.equals("1")){
            if(campoNumero1.getText().equals("")){
            campoNumero1.setText("1");
            }
            else if(campoNumero2.getText().equals("")){
                campoNumero2.setText("1");
            }  
        }
        if(numero.equals("2")){
            if(campoNumero1.getText().equals("")){
            campoNumero1.setText("2");
            }
            else if(campoNumero2.getText().equals("")){
                campoNumero2.setText("2");
            }
        }    
        if(numero.equals("3")){
            if(campoNumero1.getText().equals("")){
            campoNumero1.setText("3");
            }
            else if(campoNumero2.getText().equals("")){
                campoNumero2.setText("3");
            }  
        }
        if(numero.equals("4")){
            if(campoNumero1.getText().equals("")){
            campoNumero1.setText("4");
            }
            else if(campoNumero2.getText().equals("")){
                campoNumero2.setText("4");
            }  
        }
        if(numero.equals("5")){
            if(campoNumero1.getText().equals("")){
            campoNumero1.setText("5");
            }
            else if(campoNumero2.getText().equals("")){
                campoNumero2.setText("5");
            }  
        }
        if(numero.equals("6")){
            if(campoNumero1.getText().equals("")){
            campoNumero1.setText("6");
            }
            else if(campoNumero2.getText().equals("")){
                campoNumero2.setText("6");
            }  
        }        
        if(numero.equals("7")){
            if(campoNumero1.getText().equals("")){
            campoNumero1.setText("7");
            }
            else if(campoNumero2.getText().equals("")){
                campoNumero2.setText("7");
            }  
        }
        if(numero.equals("8")){
            if(campoNumero1.getText().equals("")){
            campoNumero1.setText("8");
            }
            else if(campoNumero2.getText().equals("")){
                campoNumero2.setText("8");
            }  
        }
        if(numero.equals("9")){
            if(campoNumero1.getText().equals("")){
            campoNumero1.setText("9");
            }
            else if(campoNumero2.getText().equals("")){
                campoNumero2.setText("9");
            }      
        }
        if(numero.equals("0")){
            if(campoNumero1.getText().equals("")){
            campoNumero1.setText("0");
            }
            else if(campoNumero2.getText().equals("")){
                campoNumero2.setText("0");
            }  
        } 
    }//GEN-LAST:event_formKeyTyped

    char operacion;
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(campoNumero1.getText().isEmpty()){
            return;
        }
        int numero1 = Integer.parseInt(campoNumero1.getText());
        char simbolo = evt.getKeyChar();
    
        if (!operacionSeleccionada){
            if (simbolo == '+') {
                operacion = '+';
                campoSimbolo.setText("+");
                operacionSeleccionada = true;
            } else if (simbolo == '-') {
                operacion = '-';
                campoSimbolo.setText("-");
                operacionSeleccionada = true;
            } else if (simbolo == '*') {
                operacion = '*';
                campoSimbolo.setText("*");
                operacionSeleccionada = true;
            } else if (simbolo == '/') {
                operacion = '/';
                campoSimbolo.setText("/");
                operacionSeleccionada = true;
            }
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(campoNumero2.getText().isEmpty()){
                return;
            }
            int numero2=Integer.parseInt(campoNumero2.getText()); 
            int resultado=0;
            switch (operacion) {
                case '+':
                    resultado = numero1+numero2;
                    break;
                case '-':
                    resultado = numero1-numero2;
                    break;
                case '*':
                    resultado = numero1*numero2;
                    break;
                case '/':
                    if (numero2!=0) {
                        resultado = numero1/numero2;
                    } else {
                        JOptionPane.showMessageDialog(null, "NO SE PUEDE DIVIDIR ENTRE O", "ERROR", JOptionPane.ERROR_MESSAGE);
                        campoNumero1.setText("");
                        campoNumero2.setText("");
                        campoSimbolo.setText("");
                        return;
                    }
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "OPERACION NO VALIDA", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return;
            }
            campoResultado.setText("Resultado: "+ resultado);
            campoNumero1.setText("");
            campoNumero2.setText("");
            campoSimbolo.setText("");
        }
           
    }//GEN-LAST:event_formKeyPressed

    private void botonNumero0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNumero0MouseClicked
        if(!operacionSeleccionada) {
            if (campoNumero1.getText().equals("")){
                campoNumero1.setText("0");
            }
        }else{
            if(campoNumero2.getText().equals("")){
                campoNumero2.setText("0");
            }
        }  
    }//GEN-LAST:event_botonNumero0MouseClicked

    private void botonNumero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero0ActionPerformed

    private void botonNumero4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNumero4MouseClicked
        if(!operacionSeleccionada) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("4");
            }
        }else{
            if(campoNumero2.getText().equals("")) {
                campoNumero2.setText("4");
            }
        } 
    }//GEN-LAST:event_botonNumero4MouseClicked

    private void botonNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero4ActionPerformed

    private void botonNumero5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNumero5MouseClicked
        if(!operacionSeleccionada) {
            if (campoNumero1.getText().equals("")){
                campoNumero1.setText("5");
            }
        }else{
            if(campoNumero2.getText().equals("")){
                campoNumero2.setText("5");
            }
        }   
    }//GEN-LAST:event_botonNumero5MouseClicked

    private void botonNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero5ActionPerformed

    private void botonNumero6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNumero6MouseClicked
        if(!operacionSeleccionada) {
            if (campoNumero1.getText().equals("")){
                campoNumero1.setText("6");
            }
        }else{
            if(campoNumero2.getText().equals("")){
                campoNumero2.setText("6");
            }
        }  
    }//GEN-LAST:event_botonNumero6MouseClicked

    private void botonNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero6ActionPerformed

    private void botonNumero7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNumero7MouseClicked
        if(!operacionSeleccionada) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("7");
            }
        }else{
            if(campoNumero2.getText().equals("")) {
                campoNumero2.setText("7");
            }
        }  
    }//GEN-LAST:event_botonNumero7MouseClicked

    private void botonNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero7ActionPerformed

    private void botonNumero8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNumero8MouseClicked
        if(!operacionSeleccionada) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("8");
            }
        }else{
            if(campoNumero2.getText().equals("")) {
                campoNumero2.setText("8");
            }
        }  
    }//GEN-LAST:event_botonNumero8MouseClicked

    private void botonNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero8ActionPerformed

    private void botonNumero9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNumero9MouseClicked
        if(!operacionSeleccionada) {
            if (campoNumero1.getText().equals("")) {
                campoNumero1.setText("9");
            }
        }else{
            if(campoNumero2.getText().equals("")) {
                campoNumero2.setText("9");
            }
        }   
    }//GEN-LAST:event_botonNumero9MouseClicked

    private void botonNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumero9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNumero9ActionPerformed

    private void botonSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSumaMouseClicked
    if(!campoNumero1.getText().equals("")){
        campoSimbolo.setText("+");
        operacionSeleccionada = true;
        }
    }//GEN-LAST:event_botonSumaMouseClicked

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed

    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRestaMouseClicked
    if(!campoNumero1.getText().equals("")){
        campoSimbolo.setText("-");
        operacionSeleccionada = true;
        }
    }//GEN-LAST:event_botonRestaMouseClicked

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonMultiplicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMultiplicacionMouseClicked
    if(!campoNumero1.getText().equals("")){
        campoSimbolo.setText("*");
        operacionSeleccionada = true;
        }
    }//GEN-LAST:event_botonMultiplicacionMouseClicked

    private void botonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMultiplicacionActionPerformed

    private void botonDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDivisionMouseClicked
    if(!campoNumero1.getText().equals("")){
        campoSimbolo.setText("/");
        operacionSeleccionada = true;
        }
    }//GEN-LAST:event_botonDivisionMouseClicked

    private void botonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDivisionActionPerformed

    private void campoSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSimboloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSimboloActionPerformed

    private void campoSimboloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoSimboloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSimboloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(miniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(miniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(miniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(miniCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miniCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDivision;
    private javax.swing.JButton botonMultiplicacion;
    private javax.swing.JButton botonNumero0;
    private javax.swing.JButton botonNumero1;
    private javax.swing.JButton botonNumero2;
    private javax.swing.JButton botonNumero3;
    private javax.swing.JButton botonNumero4;
    private javax.swing.JButton botonNumero5;
    private javax.swing.JButton botonNumero6;
    private javax.swing.JButton botonNumero7;
    private javax.swing.JButton botonNumero8;
    private javax.swing.JButton botonNumero9;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonResultado;
    private javax.swing.JButton botonSuma;
    private javax.swing.JTextField campoNumero1;
    private javax.swing.JTextField campoNumero2;
    private javax.swing.JTextField campoResultado;
    private javax.swing.JTextField campoSimbolo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
